### ISSUE TITLE
How do you add a new row to a table?

### ISSUE THREAD

**Issue by berney** [michenriksen/drawio-threatmodeling#2]
This looks really nice and neat. In the tables for Assets, Threat Actors, Security Controls, how do you add a new row?
I can get a new line with enter but its the same table cell. In your example you have multiple rows, with the lines dividing them.

Attempt:
![image](https://user-images.githubusercontent.com/3227426/104994036-f1d7ec80-5a77-11eb-980f-1e3dab098d3f.png)

Desired:
![image](https://user-images.githubusercontent.com/3227426/104994099-09af7080-5a78-11eb-9d73-aa5ed3ccdb9c.png)

I know I could draw a line in of the right colour, but is there an easier (proper) way to get a new table row?

**Comment by AXDOOMER** [comment]
Click inside an item's row, then on the right you'll see this appear. 

![image](https://user-images.githubusercontent.com/6194072/110816933-cb555700-8259-11eb-90d9-5a64c730ea07.png)

You can add rows this way.

**Comment by berney** [comment]
Thanks heaps @AXDOOMER. I had to double-click to get this. When the text cursor is in the row I see the table options for inserting new rows etc.
